### PR TITLE
Updated fonts for publication on Google Fonts

### PR DESCRIPTION
**Pull request by yanone**
Most notably, the vertical metrics were adjusted to match the previously published fonts, and the TTF files are now included in the repository as the Google onboarding code pulls them automatically from the repository.
Please accept this PR before we can continue with publishing the update. Thank you.

### CODE REVIEW

**Comment by kontur** [comment]
Thanks @yanone I'll have a look at those shortly. Thanks particularly for the vertical metrics updating; never quite sure how to deal with that with existing GF fonts, will check the outcome from your patch. I saw you spotted a few things fixed in `master` also in the meantime 👍 

A few of the naming things apply to GF but not to the rest of Rosetta's fonts, so I'm not sure if we want both, or some renaming script for GF or vice versa.

**Comment by yanone** [comment]
Sure, nice.

> A few of the naming things apply to GF but not to the rest of Rosetta's fonts, so I'm not sure if we want both, or some renaming script for GF or vice versa.

Okay, let me know your outcome. In worst case I could set up split Rosetta/GF output folders. Google now has this `upstream.yaml` file that contains source (as in source repo) to target mappings for the font files, so we can easily have two separate font folders and still enable Google’s automation.

**Comment by kontur** [comment]
Hey @yanone I merged most of the changes, but a few notes.

- I still have to confirm if we need "Rosetta" names for some of the fonts, but if needed I'll add those somehow separate
- I'd like to keep OTF files in the repo — is this a problem for the GF integration?
- Note that some (VF) folder and file names have changed since you worked on the repo — in case this affects the GF integration?
- As far as I can see the vertical metrics changes are ok, but I'll confirm with @Ancymonic 
- I've removed the axis mappings from the glyphs files — they are already set in the designspace
- The latest master also has a small feature fix for italic numero sign and alternates

Thanks for all your work 👍 
Navigating the Fontbakery output / GF requirements can be quite challenging, so your input is very much appreciated.

**Comment by yanone** [comment]
> I still have to confirm if we need "Rosetta" names for some of the fonts, but if needed I'll add those somehow separate

What are these names you're talking about?

> I'd like to keep OTF files in the repo — is this a problem for the GF integration?

Absolutely not. We need the TTFs to be present (they weren't when I picket up the work), the other formats don't matter.

> Note that some (VF) folder and file names have changed since you worked on the repo — in case this affects the GF integration?

Yes. The TTF files need to be in a stable location for the automation.

> As far as I can see the vertical metrics changes are ok, but I'll confirm with @Ancymonic

I had to take them from the fonts currently published on Google Fonts. They need the metrics to be identical to prevent regression. If this is a problem for you we need to search for solution where we host two sets of fonts in the repo, similar to what was already mentioned for the different names, if necessary.

> I've removed the axis mappings from the glyphs files — they are already set in the designspace

Yes, that was a mistake of mine. I wasn't aware at first of the mappings in the designspace.

> The latest master also has a small feature fix for italic numero sign and alternates

Cool. Please let me know your progress. Only once everything is settled, I can proceed with pushing them to Google Fonts. Ask my anytime for help.

**Comment by kontur** [comment]
Hey @yanone ! Sorry this took longer than expected. `master` should now be all ready for prime time.

**Comment by yanone** [comment]
Thanks. Looks good. I pushed it to Google Fonts today.

**Pull request merged**
