### PR TITLE
Licensing update

### PR DESCRIPTION
**Pull request by davelab6**
Include inherited Sorkin Type Co notices. 

Fixes https://github.com/rosettatype/yrsa/issues/3

### CODE REVIEW

**Comment by MrBrezina** [comment]
Thank you. We would however prefer if people are added as co-authors after consultation with us. Eben and did not work on this hence I do not think he should be included. I will correct this in future commits.

**Comment by davelab6** [comment]
Yes he is an author, no way around that, but you could not list him as a contributor, that makes sense.

**Comment by MrBrezina** [comment]
Earlier, I asked about reference to general practise in Libre community. Is there such a document?

**Comment by davelab6** [comment]
Not really; I have begun maintaining https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md and there is https://github.com/raphaelbastide/Unified-Font-Repository but I want to make some pull requests to it as I think it isn't ideal

**Comment by davelab6** [comment]
(updated earlier comment)

**Pull request merged**
